<?php
// $Id $

/**
 * @file
 *  extra.module 
 */

/**
 * Implementation of hook_menu().
 */
function extra_menu() {
  $items = array();

  $items['admin/settings/extra'] = array(
    'title' => t('Extra Features'), 
    'description' => t('Show/Hide features to users without "administer features" permissions'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('extra_admin_settings'),
    'access arguments' => array('administer extras'), 
    'type' => MENU_NORMAL_ITEM,
    'file' => 'extra.admin.inc', 
  );

  return $items;
}

/**
 * Implementation of hook_formalter().
 */
function extra_form_alter(&$form, $form_state, $form_id) {
  // Alter Features form
// dsm($form_id);
  if ($form_id == 'features_admin_form') {
    // Each feature module has a group (e.g. features).
    // Under that group, each module is represented under
    // $form['group']['status']
    // $form['group']['sign']
    // $form['group']['state']
    // $form['group']['actions']
    //
    // I assume they could have items here too, these must
    // be optional: 
    // $form['group']['action']
    // $form['group']['weight']
    // $form['group']['links']

/****
Roadmap: 
featuresets module:
- featuresets module should let users define "groups"
- featuresets module should let users associate features 
  modules with designated groups
- featuresets module: Reorganize features into featuresets

instructions module: 
- add a tab for Instructions on admin/build/features
  next to Create and Manage
- Use theme('features_form') to put instructions in 
  familiar interface
- Provide instructions for enabled modules

skin module: 
- add a tab for Skin on admin/build/features
- form alter this, replacement for bloated subtheme form
- skin admin GUI for adding elements to skin page then exporting w/ Create Features

TBD
- mechanism for hiding feature modules from ___ users under ___ 
  conditions
//**/

//dsm('extra runs here');
//dsm($form, 'form');
    $form['features']['status']['ax2'] = $form['ax']['status']['ax2'];
    unset($form['ax']['status']['ax2']);
//dsm($form['#features']);
  }
}
